[project]
name = "sift-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.1",
    "notebook>=7.4.0",
    "numpy>=2.2.5",
    "opencv-python>=4.11.0.86",
]
